#!/bin/bash


while true; do
  read line;
  case "$line" in
    +)
      kill -USR1 $(cat .pid)
      ;;
    \*)
      kill -USR2 $(cat .pid)
      ;;
    "TERM")
      kill -15 $(cat .pid)
      ;;
  esac
done
        
